#æµ‹è¯•åœ°å€
#è¿™é‡Œè¾“å…¥ä¼ä¸šå¾®ä¿¡æœºå™¨äººåœ°å€ğŸ‘‡
#webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/*********"

article_source: "local"
local_article_path: "articles/"
log_path: "logs/"  # æ–°å¢æ—¥å¿—ç›®å½•é…ç½®

deepseek:
#è¿™é‡Œè¾“å…¥deepseekçš„apiï¼Œå»å®˜ç½‘ä¹°10å—é’±æœ¬è½¯ä»¶èƒ½ç”¨ä¸€å¹´
  api_key: "sk-****************a"
  model: "deepseek-chat"
  api_base: "https://api.deepseek.com/v1"
  temperature: 0.8
  max_tokens: 800
